### ISSUE TITLE
Why hash the back of cards?

### ISSUE THREAD

**Issue by mkarrmann** [abletsoff/joplin-anki-sync#2]
This is really neat, thanks for making this!

I'm just curious why the back of the cards are being hashed.

Honestly I can't even think of a reason why you'd want to hash the back of the cards like this, it seems to completely remove the usefulness of this tool. What use is the hash of the card when I'm studying flash cards? I'll probably fork this repo and remove the hashing, but at this point I'm just genuinely curious why the hash was added- is there some usecase I'm overlooking?

Only things I can come up with are:

1. The intention of the hashing the contents was to optimize string comparison, but a logic error meant the stored hash itself is stored as the back of the card (seems very unlikely considering how clean and well-functioning everything else is and how completely obvious this bug is)
2. Just a troll- makes the tool only useable to someone who can modify the Python source code

**Comment by abletsoff** [comment]
The tool was created to leverage two learning techniques: active recall and spaced repetitions.
During my repetition workflow am using both Anki and Joplin app.
Anki is used only as platform for scheduling spaced repetition. Joplin is used right after active recall to make sure that I understand the topic (e.g. Cache poisoning) correctly.

When creating the tool, I try to achieve simplicity and stability.
Of course, it would make more sense to store the contents of the Joplin topic on the back of an Anki flash card. But during the architecture design, I considered the following obstacles:
- As far as I know, the default markdown view in Anki is not supported. I often use markdown functions (for example, image rendering, code blocks, ...) in my Joplin notes 
- Anki extension that supports markdown may be unstable and may not support some functions (for example, building mermaid diagrams).
- It will be additional complexity to find image recourse in Joplin folder and paste it to the Anki. Also path to Joplin folder may differ between installation options and operation systems.
- It will be additional complexity to compare Anki flashcard images and Joplin topic images.

The hash is only used to determine whether the content of the Joplin topic has been changed since the last synchronization with Anki. And if this is the case, then the repetition of the Anki card should be rescheduled.

**Comment by mkarrmann** [comment]
@abletsoff Thanks so much! I didn't think about using the tool that way- that both makes sense and is clever!

Would you be open to a PR which updates the README to clarify this is the intended use of the tool. This is one of the top results on Google when searching for this sort of thing, and I imagine others will have a confusion similar to mine.
